wso2:
  connector:
    mysql:
      enabled: true
    host: wso2is-rdbms-service-mysql
    port: "3306"
    username: wso2carbon
    password: wso2carbon
    driverClass: com.mysql.jdbc.Driver
    validationQuery: "SELECT 1"
    defaultAutoCommit: "false"
  subscription:
    username: ""
    password: ""
  deployment:
    wso2is:
     dockerRegistry: "asia.gcr.io"
     imageName: "testgrid/wso2-docker/wso2is"
     imageTag: "5.8.0-centos-adopt_open_jdk8-mysql"
     replicas: 1
     minReadySeconds: 30
     strategy:
       rollingUpdate:
         maxSurge: 1
         maxUnavailable: 0
     livenessProbe:
       initialDelaySeconds: 250
       periodSeconds: 10
     readinessProbe:
       initialDelaySeconds: 250
       periodSeconds: 10
     resources:
       # These are the minimum resource recommendations for running WSO2 Identity server profiles
       # as per official documentation (https://docs.wso2.com/display/IS580/Installation+Prerequisites).
       requests:
         memory: "2Gi"
         cpu: "2000m"
       limits:
         memory: "4Gi"
         cpu: "4000m"
     imagePullPolicy: Always
  centralizedLogging:
    enabled: false
    logstash:
      imageTag: 7.2.0
      elasticsearch:
        host: wso2-elasticsearch-master
        username: "elastic"
        password: "changeme"
      indexNodeID:
        wso2ISNode: "wso2is-node"

kubernetes:
  svcaccount: "wso2svc-account"
